Added examples for spatial features
oracle/oracle-db-examples pull request #124
Opened 2020-09-28 07:06 UTC by ryotayamanaka

Spatial and Graph product management team would like to add a directory "spatial/" for adding the examples and supplemental materials for Spatial features of Oracle Database. This change includes the demo codes for using Map Visualization Component and Map API as the README file in each directory describes.

2020-09-28 13:24 UTC, jayant62 commented
This directory (and the one which will be created for Graph) will only contain sample code that conforms to the relevant standards and guidelines. We have been through the process for another repo and hence are familiar with it.

2020-09-28 21:38 UTC, gvenzl requested changes
Please also add an entry for that top-level directory in the main ReadMe (https://github.com/oracle/oracle-db-examples/blob/master/README.md)

2020-09-30 02:44 UTC, ryotayamanaka commented
Thank you for your review. I have added the entry!

2020-10-05 16:59 UTC, gvenzl approved these changes

2020-10-05 16:59 UTC, merged